### ISSUE TITLE
There is no support for the password protect

### ISSUE THREAD

**Issue by BlackSkorpio** [notandigg/grimsi-geysir#17]
It seams since you `<koken:load source="albums" limit="{{ settings.album_count }}" order_by="modified_on" order_direction="desc">`
This breaks the password protect

If instead would be using `<koken:load limit="{{ settings.album_count }}" order_by="modified_on" order_direction="desc">` You would not break the PW protect

**Comment by notandigg** [comment]
I would need to have the password protect plugin to test it out fully. I don't have it to give better support for the plugin.
