### ISSUE TITLE
If you for some reason link to a empty album it breaks the whole theme

### ISSUE THREAD

**Issue by BlackSkorpio** [notandigg/grimsi-geysir#18]
If you have an empty album that you have a link to, clicking on that will break the whole theme

**Comment by notandigg** [comment]
Hi, hope all is good by you.
I'm going over all the issues and closing the ones fixed. Could you please give me an example how I can replicate this?

**Comment by notandigg** [comment]
I have tested this out and I can't seem to be able to replicate this error. I could have already fixed it.
