### ISSUE TITLE
Footer settings feels more as they should be global and not scoped for every single template (v1.5.0)

### ISSUE THREAD

**Issue by BlackSkorpio** [notandigg/grimsi-geysir#2]
Mostly if I would like to turn of the footer, I would turn it of site wide, not per template

**Comment by notandigg** [comment]
The reason for this is that you can hide the footer only for index page but show it on other pages. I did it like this instead of creating two settings.

**Comment by notandigg** [comment]
Changed the behaviour in version 1.6.0
