### ISSUE TITLE
Albums appear to be limited to ~100 pictures

### ISSUE THREAD

**Issue by vanElden** [notandigg/grimsi-geysir#24]
Thanks for a very nice theme!

I have several albums containing more than 100 pictures; it looks as if these albums get cut at ca. 100. Sometimes it's 97, sometimes 99.

I had a very quick look through the code, but didn't see an obvious limitation. Maybe you can point me into some direction, then I'd be happy to investigate further and create a pull request.

**Comment by notandigg** [comment]
Hi and thanks for the interest in my theme. Are you talking about limitation in listing albums or content inside the albums? If you could send me a link so I can take a look.

**Comment by vanElden** [comment]
Wow, I did not expect to get an answer so fast!

I'm talking about content inside an album. I've temporarily switched this to Public, so you can have a look:
[redacted]

That album has 385 pictures, and if you look at them through the Lightbox/Slideshow they show up just fine. But only 100 appear in the grid. I've realized that it's probably always exactly 100; the 100th just isn't necessarily in the bottom row.

Thanks!

**Comment by notandigg** [comment]
Ahh I see now. I’ll have a look, I might have already fixed it in 1.6.1 which will come next. If not I’ll add it to the list and it will come with next release. Thanks for bringing it to my attention :-)

**Comment by vanElden** [comment]
Hi again

I was able to fix this myself after all. See Pull Request.

Thanks again! My site is now looking exactly as I wanted it to!

**Comment by notandigg** [comment]
Thanks again for pointing out the album limit. I have now released version 1.6.1 Please feel free to download it and test it out. And if you find any more bugs please add a new issue.
