### ISSUE TITLE
Edit Sections 

### ISSUE THREAD

**Issue by scurfin** [notandigg/grimsi-geysir#26]
Is it possible to choose which sections are displayed on the front page besides editing the slideshow-sections.html?

Also, I would like to show a section with the featured albums on the front page.

**Comment by notandigg** [comment]
Yes has been on my todo list. Stay tuned.

**Comment by scurfin** [comment]
Thanks for the quick answer.
Thats nice to hear. In the meantime I will make my own custom template for experiments.

**Comment by notandigg** [comment]
Now I've added the option to show/hide sections on front page in version 1.6.2
