### ISSUE TITLE
Wrong link to lightbox with certain album title

### ISSUE THREAD

**Issue by scurfin** [notandigg/grimsi-geysir#30]
Hey,

I think I found an rare issue with certain album titles and the lightbox links, but not entirely sure it is theme related.

The problem:
If an album is named somethink like "Tag des offenen ..." (german for day of open...) the link would be domain.com/alben/tag-des-offenen/inhalt/.... These links are correct for album view or single image view. But the lightbox link on the single image view suddenly is domain.com/alben/tag/-des-offenen/inhalt/.... with an additional / after the word tag and the site is loading endlessly and the lightbox does not appear.

If I remove the dash between "tag" und "des" (domain.com/alben/tagdes-offenen/inhalt/...) all the links including lightbox are fine and working.

I think, something is interpreting the word "tag" as the english word? Because on my site the link domain.com/tag/ seems to exist.

**Comment by notandigg** [comment]
> Hey,
> 
> I think I found an rare issue with certain album titles and the lightbox links, but not entirely sure it is theme related.
> 
> The problem:
> If an album is named somethink like "Tag des offenen ..." (german for day of open...) the link would be domain.com/alben/tag-des-offenen/inhalt/.... These links are correct for album view or single image view. But the lightbox link on the single image view suddenly is domain.com/alben/tag/-des-offenen/inhalt/.... with an additional / after the word tag and the site is loading endlessly and the lightbox does not appear.
> 
> If I remove the dash between "tag" und "des" (domain.com/alben/tagdes-offenen/inhalt/...) all the links including lightbox are fine and working.
> 
> I think, something is interpreting the word "tag" as the english word? Because on my site the link domain.com/tag/ seems to exist.

Hi,
can you send me a link to the problem page so I can try and reproduce the problem? It sounds like a Koken core problem.

**Comment by scurfin** [comment]
Hey,

I create a new album (Tag des Testes) for testing:

[REDACTED]

The corresponding wrong link on the detail view:
[REDACTED]

The correct link manually entered is working: 
[REDACTED]

Now I am noticing, that an aditional /tags/des-test/ is entered before 
the album part in the URL.

**Comment by notandigg** [comment]
> Hey, I create a new album (Tag des Testes) for testing: /alben/tag-des-test/inhalt/buntstiftspitze/ The corresponding wrong link on the detail view: /tags/des-test/alben/tag-des-test/inhalt/buntstiftspitze/lightbox/ The correct link manually entered is working: /alben/tag-des-test/inhalt/buntstiftspitze/lightbox/ Now I am noticing, that an aditional /tags/des-test/ is entered before the album part in the URL.

I'm wondering, if you try and remove the "tag-" from the title, does the problem still exist? And is it only this that is not working or are there more?

**Comment by scurfin** [comment]
A workaround is to only edit the link in the album settings on the right menu sidebar:
[REDACTED] (Removed the first dash)
Now the lightbox link is correct.

**Comment by notandigg** [comment]
> A workaround is to only edit the link in the album settings on the right menu sidebar:
> Now the lightbox link is correct.

I have tested it on my website (adding tag-) in front of a link, it acts the same. So I would say it is a problem with how Koken works. Even though Tag means day in German, Koken reads it as tag and gets confused of "koken tag" :-) So I'm going to close this issue. But I would recommend that you report this issue to koken. Can go here and post about this issue: https://github.com/koken/issues

*This is only related to the link, you should still be able to use the same album title but change url only

**Comment by scurfin** [comment]
Thanks for your help!

I've reported the issue to koken.
Could you please delete the links to my site in your quotes?

**Comment by notandigg** [comment]
> Thanks for your help!
> 
> I've reported the issue to koken.
> Could you please delete the links to my site in your quotes?

No problem - I've removed the links.
