### ISSUE TITLE
The slide down menu wont close when clicking beneath it

### ISSUE THREAD

**Issue by BlackSkorpio** [notandigg/grimsi-geysir#8]
Only tested this on your own site...
Clicking outside the menu either the right or left side closes the menu.
But when you click beneath it, it stays open

Tested with FF 53.0.2 Win7

**Comment by notandigg** [comment]
This is fixed in next update

**Comment by notandigg** [comment]
This is fixed in next update

**Comment by notandigg** [comment]
fixed in version 1.6.0
